### ISSUE TITLE
OreSat0.5 2U: 20 pin AUX connectors in the wrong slot. :(

### ISSUE THREAD

**Issue by andrewgreenberg** [oresat/oresat-backplane#17]
20 pin aux connectors need to be in slot 17 (CFC Processor Card) and slot 18 (CFC sensor card), not in Slot 19, which is where the lens mount holders go.. You can leave the main connector in slot 19, no harm in that, but it does not need the AUX connector.

**Comment by Benjamin-C** [comment]
Moved to 17 and 18
